### PR TITLE
Search filters from url - decks page edition

### PR DESCRIPTION
**Pull request by alexmiddeleer**

### CODE REVIEW

**Comment by alexmiddeleer** [comment]
@lily-pytel Last one for search filters in the url, I promise!

**Comment by lily-pytel** [comment]
It might be what is causing the tests to fail as well

**Comment by alexmiddeleer** [comment]
> Nice! Only thing is that we'll only show decks from the last 150 days now, right? That's intentional? My only concern is that there no way to know that it's what happening (there's no showing x out of y like PUMA has)

Well, I am just trying to match it to the form default. This is prod, but it's not actually the last 150 days - it's all of our decks.

image

**Comment by lily-pytel** [comment]
@alexmiddeleer you're right, fair enough

**Pull request merged**
