### PR TITLE
Add Impel to Articles page

### PR DESCRIPTION
**Pull request by PapaCapricorn**
Implementing this request from Noah: 

`If we could also make a late inclusion to the articles page, another source has started producing content and diversifying that page a bit more would be splendid.
This article should be added to the articles page: https://teamdgn.net/2019/09/27/the-many-uses-of-impel/`

### CODE REVIEW

**Comment by PapaCapricorn** [comment]
@lily-pytel I would tend to agree with you about the re-writes, but to clarify: this summary was just copied directly from the article itself, it did not originate with me or MGH. We might choose to use a shorter or longer excerpt, but it would feel awkward to me to re-write someone else's copy unless it was something they asked for.

**Comment by lily-pytel** [comment]
@PapaCapricorn ah, I see. Never mind then!

**Comment by lily-pytel** [comment]
@alexmiddeleer any reason not to merge this?

**Comment by PapaCapricorn** [comment]
Merge away plz :)

**Pull request merged**
