### PR TITLE
Hide spawns

### PR DESCRIPTION
**Pull request by alexmiddeleer**
Just the database pieces in this PR. Next PR will contain the graphql updates.

### CODE REVIEW

**Comment by alexmiddeleer** [comment]
turned out not to be so bad, so ignore what I said before - this PR has everything.

**Comment by lily-pytel** [comment]
Interesting, so is there any way to see that spwan card?

**Comment by alexmiddeleer** [comment]
@lily-pytel Only by clicking on a card that spawns something e.g. https://www.mythgardhub.com/card?id=329

**Comment by lily-pytel** [comment]
Ah so does that card in the example database - is it attach to one of the other cards?

**Comment by alexmiddeleer** [comment]
@lily-pytel nope not right now. I just wanted to create it so that I could verify it does not appear in searches

**Comment by alexmiddeleer** [comment]
We already have a card that spawns other cards, but those spawns are not spawnOnly = true. Which could perhaps happen if a card spawns a true clone, such as https://scryfall.com/card/znr/203/scute-swarm (not sure if can happen in Mythgard but maybe someday)

**Review by lily-pytel — APPROVED** [review]
Looks great!

**Pull request merged**
