### PR TITLE
Tabs for mods page

### PR DESCRIPTION
**Pull request by alexmiddeleer**

### CODE REVIEW

**Comment by lily-pytel** [comment]
The code itself looks fine but all the graphql calls hang forever, same with trying to login with google. Was it some version update?

**Comment by alexmiddeleer** [comment]
The Travis failures don’t seem to be connected to new code changes. I tried making a PR from master with no code changes and it’s the same outcome https://github.com/mythgard-hub/mythgard-hub/pull/307. I’ll look into it more tonight.

**Comment by lily-pytel** [comment]
Yeah, saw that and also saw that locally the site doesn't actually work for me. The pages open but all graphql requests just hang, so that might be why the tests are failing

**Comment by alexmiddeleer** [comment]
Oh okay, I’ll try to nuke everything and try again locally. It was working
for me but docker images might need to be refreshed.

**Comment by alexmiddeleer** [comment]
@lily-pytel can you try with `docker-compose up --force-recreate`? I'm not sure what else to try to get graphql to hang...

**Comment by lily-pytel** [comment]
I can't get it to not hang so I will investigate which version probably got updated without our knowledge

**Comment by alexmiddeleer** [comment]
@lily-pytel on travis it seems to be next that is hanging... I had it output some logs. https://travis-ci.com/github/mythgard-hub/mythgard-hub/builds/199507560

**Pull request merged**
