### PR TITLE
Fix the issue by search by each word (the deck name must have all words)

### PR DESCRIPTION
**Pull request by Edswor**
Fix the issue by search by each word (the deck name must have all words)

### CODE REVIEW

**Comment by lily-pytel** [comment]
Fixes #186

**Comment by lily-pytel** [comment]
@Edswor it would be great to add this to the e2e tests (`decks-page.js` specifically)

**Comment by Edswor** [comment]
Sure, I'll add the test cases (once I learn how it works :) ).

**Comment by alexmiddeleer** [comment]
Sorry, didn't mean to close.

**Comment by Edswor** [comment]
I have added test to e2e and also a fix when there are several spaced between words.

**Comment by Edswor** [comment]
Cancel/close this pull request in favor of "Fix deck search error message input with spaces 2" (It has the test to e2e and also a fix when there are several spaced between words.)

**Pull request closed without merging**
