### PR TITLE
Add dev dependencies for prettier linting with eslint

### PR DESCRIPTION
**Pull request by evsheffield**
I wasn't sure if folks had been doing this with global installs, but figured it would be helpful to just have things in place as dev dependencies so we can just `npm install` and go.

### CODE REVIEW

**Comment by jtrussell** [comment]
Yay! Thanks for this 👍.

**Comment by jtrussell** [comment]
This looks good to me, but perhaps @alexmiddeleer can weigh in as I'm less familiar with prettier configs.

**Comment by evsheffield** [comment]
FWIW I did test it out with both Sublime and VS Code linter plugins and it seemed to be working. The only slightly funky thing is that both editors look for the node_modules to be in the project root (perhaps the plugins are configurable to change this) so rather than pull in the whole "mythgard-hub" folder I added each of the sub-projects to the workspace individually.

**Comment by alexmiddeleer** [comment]
Lgtm, thanks

**Pull request merged**
